### ISSUE TITLE
Uninstall-PSResouce fails if 'C:\Program Files\PowerShell\Modules' does not exist

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#217]
PSGet beta 8 fails when trying to uninstall a module if an optional install location does not exist.

```powershell
C:\> Get-Module pester -ListAvailable

    Directory: C:\Users\Thomas\Documents\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     5.0.3                 Pester                              Desk      {Invoke-Pester, Describe, Context, It…}
Script     5.0.2                 Pester                              Desk      {Invoke-Pester, Describe, Context, It…}
Script     4.9.0                 Pester                              Desk      {Describe, Context, It, Should…}

C:\> Uninstall-PSResource Pester-Verbose
Uninstall-PSResource: Could not find a part of the path 'C:\Program Files\PowerShell\Modules'.

C:\> Test-Path "C:\Program Files\PowerShell\Modules"
False
```

**Comment by alerickson** [comment]
Thanks @ThomasNieto!  This will get resolved in the next release

**Comment by ThomasNieto** [comment]
Thanks @alerickson. Might also want to check to see if this issue also occurs on install or any of the checked folders does not exist.

**Comment by alerickson** [comment]
@ThomasNieto yup, it was happening in install as well, will do a more thorough check to make sure this isn't happening elsewhere.

**Comment by SydneyhSmith** [comment]
Closing this as resolved

**Comment by ThomasNieto** [comment]
@alerickson / @SydneyhSmith when was this issue resolved? I still get the error with `Get-PSResource` on beta 10.

```powershell
C:\> Get-PSResource

Get-PSResource: Could not find a part of the path 'C:\Program Files\PowerShell\Modules'.
```

**Comment by SydneyhSmith** [comment]
Thanks @ThomasNieto I can repro this as well, I will re-open the issue, apologies for closing it!

**Comment by alerickson** [comment]
This will be resolved with the release of Preview 11.
