### ISSUE TITLE
[3.0.0-beta10] Install-Module fails with OneDrive - Access to cloud file is denied

### ISSUE THREAD

**Issue by wsmelton** [PowerShell/PSResourceGet#300]
PowerShellGet Version: 2.2.5/3.0.0-beta
PowerShell: Windows PowerShell 5.1

This issue does not exist with version 2.2.4.1. I'm on a corporate machine so our profile is tied to OneDrive, hence my Documents folder is stored there as well. I'm not sure if this may be related to what was reported on #262 but cannot confirm because policy blocks me from disabling the Files-On-Demand setting for OneDrive.

### Repo steps:

1. Install PowerShellGet 2.2.5
1. Run `Install-Module <any module>`
1. Receive error `PackageManagement\Install-Package : Access to the cloud file is denied`

Attaching the verbose output for reference:

[failed_output_2.2.5.txt](https://github.com/PowerShell/PowerShellGet/files/5505825/failed_output_2.2.5.txt)

### Additional

I have also repeated the repo steps for the 3.0.0-beta and receive the same error but in various scenarios.

If I have 2.2.5 installed as well then the 3.0.0 seems to reference the 2.2.5 version of PSModule file:

```
[PS 5.1] [22:01:09] [ 82.0ms ] C:\Users\SMelton
 [2] > ipmo PowerShelLGet -RequiredVersion 3.0.0
[PS 5.1] [22:01:18] [103.0ms ] C:\Users\SMelton
 [3] > Get-Module PowerShelLGet

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     3.0.0      PowerShelLGet                       {Find-PSResource, Get-PSResource, Get-PSResourceRepository...


[PS 5.1] [22:01:22] [ 25.0ms ] C:\Users\SMelton
 [4] > Install-Module Pester -AllowPrerelease -Force
PackageManagement\Install-Package : Access to the cloud file is denied
At C:\Users\SMelton\OneDrive - Thycotic
Corporate\Documents\WindowsPowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1:9711 char:34
+ ... talledPackages = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exce
   ption
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.RemoveItemCommand,Mic
   rosoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

I delete 2.2.5 completely and then install 3.0.0-beta10, upon import in a new session I get the `Access to the cloud file is denied` on the initial import. I issue the import again and it succeeds, but on the call to `Install-Module` the error still occurs, this time referencing the 2.2.4.1 PSModule file:

![image](https://user-images.githubusercontent.com/11204251/98456639-ca92a400-2145-11eb-8e9a-a845a80880c2.png)

**Comment by anamnavi** [comment]
@wsmelton Thanks for bringing this issue to our attention! We plan to resolve this in PowerShell 3.0

**Comment by wsmelton** [comment]
Is there any ETA on the release of 3.0 or a new beta where this will be resolved?

It is a bit of a pill to have to explain this error for users when they hit problems trying to install modules I've published as prerelease. This problem exists all the way back to 2.0.0 release of PowerShellGet (when I gave up testing).

**Comment by rivir** [comment]
Looks like this may be a larger issue with System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.RemoveItemCommand 
similar to https://github.com/PowerShell/PowerShell/issues/9246
trying command remove-item on a \WindowsPowerShell\Modules\ sub-directory (inside the OneDrive folder) comes back with a similar error
"remove-item : Access to the cloud file is denied"
FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.RemoveItemCommand

**Comment by lborgman** [comment]
I see this error in VSCODE. I just followed the recommendation that VSCODE gave me for the PowerShell terminal. (Debugging Node.js)

**Comment by kocic11** [comment]
Same issue here, VS Code asks for the upgrade and then fails:
powershell.exe -NoLogo -NoProfile -Command 'Install-Module -Name PackageManagement -Force -MinimumVersion 1.4.6 -Scope CurrentUser -AllowClobber'
PackageManagement\Install-Package : Access to the cloud file is denied
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exce
   ption
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.RemoveItemCommand,Mic
   rosoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

What cloud file does it try to access?

**Comment by SteveL-MSFT** [comment]
This should be fixed with https://github.com/PowerShell/PowerShell/pull/14860 as the problem is in PowerShell FileSystemProvider not handling reparse point directories correctly

**Comment by wsmelton** [comment]
@SteveL-MSFT does that mean this fix will not be pushed down to Windows PowerShell?

**Comment by mstassencentralbuild** [comment]
@SteveL-MSFT Please provide an update as to when the fix for this will be released as this is preventing me from removing the SharePointPnPPowerShellOnline package to upgrade to the newly PnP.PowerShell.

**Comment by ofmmmmm5** [comment]
@SteveL-MSFT Had same issue with Windows powershell. Would like to know when will the fix be released? I am currently blocking on this

**Comment by ofmmmmm5** [comment]
@alerickson I followed CG admin's email to reach out to you for help here. Please let me know if you need any additional details regarding to my issue.

**Comment by ForteUnited** [comment]
Can we get some serious attention on this issue. Basically completely roadblocked here and from my interweb searches I'm not the only one. What am I supposed to do? Completely uninstall/remove/disable onedrive from my Win 10 machine? Turn off Files On Demand and download over a terabyte of data to my local machine just to make this work? What is the work around here? This seems to be an issue that was posted back in November for crying out loud.

**Comment by alerickson** [comment]
@ofmmmmm5 @ForteUnited the issue's being addressed in [PR](https://github.com/PowerShell/PowerShell/pull/14902).  I'm working on seeing if we can get this into the next release since it's a critical issue.  I'll update this thread with a timeline of the release.

There are work arounds, such as [updating your PSModulePath](https://docs.microsoft.com/en-us/powershell/scripting/developer/module/modifying-the-psmodulepath-installation-path?view=powershell-7.1) so that the default path is not a OneDrive path.  However the one thing I'd note here is to update it so that the path you'd like to add comes before the other (deprioritized) paths.

$env:PSModulePath = "$([System.IO.Path]::PathSeparator)$MyModulePath" + $env:PSModulePath

**Comment by leonidasthe300** [comment]
@alerickson Changing PSModulePath don't work as work around for Uninstall-Module error, as all modules were installed tied to user's profile onedrive. Is there another one to be done until release?

**Comment by ofmmmmm5** [comment]
@alerickson I saw your change merged. May I know if the latest release include your changes?

**Comment by Atreidae** [comment]
I've even tried forcing the files to be local and shutting down the OneDrive client as a temp workaround, by checking the PSModulePath that points to the users OneDrive and setting it to "Always on this device" 
![image](https://user-images.githubusercontent.com/8736291/118391231-9361fa00-b676-11eb-9d29-8f59fb753d90.png)


Then waiting for the icon on the folder to update from the Syncing icon to the Green Tick 
![image](https://user-images.githubusercontent.com/8736291/118391239-9d83f880-b676-11eb-94b4-f5b63919e2ba.png)
![image](https://user-images.githubusercontent.com/8736291/118391295-ed62bf80-b676-11eb-9910-a42c37635985.png)


and waiting for Onedrive Client and wait for sync to complete
![image](https://user-images.githubusercontent.com/8736291/118391286-df14a380-b676-11eb-8dbb-1bae7c55b458.png)
![image](https://user-images.githubusercontent.com/8736291/118391309-fc497200-b676-11eb-9b8b-d7a4ea01c8e0.png)

Closing my OneDrive client
![image](https://user-images.githubusercontent.com/8736291/118391425-8d204d80-b677-11eb-8e90-33ae9a56801e.png)


And trying to install the module install again, No-Bueno.
![image](https://user-images.githubusercontent.com/8736291/118391438-a0cbb400-b677-11eb-833b-8d4e2456e8ec.png)

**Comment by ClassANetwork** [comment]
It's June, still having the issues that OP and others are having in this thread.

I am using Powershell v5.1 on 21H1


```
PS C:\Users\RobertGraham> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1023
```

Is there any ETA on a fix for this? This has been open since November of last year. It is currently a work stoppage for me and my company to effectively manage our customer's Azure tenants.

**Comment by anamnavi** [comment]
@ClassANetwork thanks for reaching out, we plan to do a release in ~2 weeks and then the update from the PowerShellGet side should address this issue

**Comment by aaronnavratil** [comment]
this workaround worked for me - adapted from above; this simply adds a leading semi-colon, but appears to resolve it.

$module = "module to install"

$env:PSModulePath = "$([System.IO.Path]::PathSeparator)" + $env:PSModulePath

if (-not (Get-Module -ListAvailable $module)) {
    Install-Module $module -Scope CurrentUser -Confirm:$false -Force -AllowClobber
}

**Comment by crshovrd41** [comment]
Hey @anamnavi - any updates here? Been a month since July 18 and your last update. I’m still seeing the issue as of 5 minutes ago.

**Comment by alerickson** [comment]
Hi @crshovrd41 we released 3.0.11-beta this week.  Can you try that version and let us know if you’re still encountering the same issue?

**Comment by justin-newman** [comment]
I was able to confirm that 3.0.11-beta was able to successfully uninstall a package where I was having the same 'Access to the cloud file is denied' error that is described in this issue. I never had an issue with install-module.

Anyway, using PowershellGet 3.0.11 and the new command Uninstall-PSResource it uninstalled just fine. Now to refactor my scripts for the future.

**Comment by alerickson** [comment]
I'm going to close this issue.  If anyone has this or a similar issue, please feel to comment here and we can reopen.

**Comment by JeremyTBradshaw** [comment]
@alerickson I am having this issue with trying to install and/or update Microsoft.Graph.Mail.  I'm on Windows 10 (stuck at 20H2 due to slow company) and have changed my $env:PSModulePath to include a non-OneDrive path.  It seems like this module in particular doesn't due good enough due dilligence and A) insists on installing the dependent module Microsoft.Graph.Authentication (which is already installed, and the latest), and refused to use PowerShellGet 3.0.12 in my CurrentUser and instead goes with 2.2.5 from ProgramFiles.

Sort of annoying to have no way to twist this things arms into submission.  Is it possible that some modules are being written in some way that invokes this problem (e.g., the Az module was popular with this issue, now so is Microsoft.Graph.Mail) ?  Or is this issue purely the fault of the client side?

**Comment by JeremyTBradshaw** [comment]
I cannot believe this issue sits here, closed as if it's actually resolved.  This is a worldwide extremely annoying issue.  Just want to crumple this entire thread and throw it in the garbage.

**Comment by ihoel** [comment]
@alerickson , we still have this issue with Microsoft.RDInfra.RDPowerShell

any chance to get it fixed?
