### ISSUE TITLE
Remove Microsoft.Extensions.Logging from csproj, improve Verbose and Debug logging

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSResourceGet#97]
I noticed that Microsoft.Extensions.Logging is used in this project. This means that until we sort out how to use loadercontext, any modules that use this logging framework will be essentially pinned to that version since this module will effectively become ubiquitous.

Are there any major concerns or plans for that?

**Comment by alerickson** [comment]
Hi @JustinGrote I just looked into this, looks like we don't need at all.  I had included it to log info from the nuget v3 protocol [catalog reader](https://docs.microsoft.com/en-us/nuget/guides/api/query-for-all-published-packages#catalog-sdk) I implemented, but was not actively using it.  I'm collecting verbose and debug info for the reader, so can still gather enough information for debugging purposes that way. 

As a side note, thank you for your extensive testing and bug finding with the preview!

**Comment by JustinGrote** [comment]
@alerickson  just wanted to follow up on this, there still does not appear to be a way to get really good logs about what's going on without running the c# debugger, where in the roadmap will be the logging to verbose/debug output added? I think that's critical before RC status.

**Comment by alerickson** [comment]
Agreed,  I'll have both of those fixed for the next release
